repository:
  name: grid
  description: Grid has moved to end-of-life status.
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
  archived: true
