#!/bin/bash

rm -rf /output/0.1/*

until PGPASSWORD=$PASSWORD psql -h $HOST -d $DATABASE -U $USER -c '\q'; do
  >&2 echo "Database is unavailable - sleeping"
  sleep 1
done

grid -vv database migrate \
    -C postgres://grid:grid_example@db/grid

java -jar schemaspy/schemaSpy.jar \
    -t pgsql11 -host $HOST -port $PORT \
    -db $DATABASE -u $USER -p $PASSWORD -o /output/0.1 \
    -dp /org/schemaspy/drivers/postgresql-42.1.1.jre7.jar
